dubbo:
  protocol:
    prot: 20880
    name: dubbo
  application:
    name: login-product
  registry:
    address: zookeeper://127.0.0.1:2181
  packageName: com.product.serviceImpl

server:
  port: 8084